### ISSUE TITLE
dimples build issue

### ISSUE THREAD

**Issue by wocsigint** [waferbaby/dimples#2]
Hello,

When I try to make `dimples build` I get this :

```
/usr/local/lib/ruby/gems/2.4.0/gems/dimples-2.7.0/bin/dimples:63:in `<top (required)>': undefined method `Site' for Dimples:Module (NoMethodError)
	from /usr/local/bin/dimples:22:in `load'
	from /usr/local/bin/dimples:22:in `<main>'
```
Can you help please ? I'm on a debian stretch fresh install.

**Comment by waferbaby** [comment]
Ooh - what does your directory layout look like, where you're running it?

**Comment by waferbaby** [comment]
It's me, not you - just pushed a new version that should fix this. Give it another shot?

**Comment by wocsigint** [comment]
Maybe I miss something because I still having an error. Let me explain how I do :
```
git clone https://github.com/waferbaby/dimples.git site1/
cd site1/
bundle install
dimples build
```
`dimples build` return this after your update :
```
/home/will/site1/lib/dimples/logger.rb:5:in `<module:Dimples>': superclass mismatch for class Logger (TypeError)
	from /home/will/about/lib/dimples/logger.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/dimples-2.7.1/bin/dimples:59:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/dimples-2.7.1/bin/dimples:58:in `glob'
	from /usr/local/lib/ruby/gems/2.4.0/gems/dimples-2.7.1/bin/dimples:58:in `<top (required)>'
	from /usr/local/bin/dimples:22:in `load'
	from /usr/local/bin/dimples:22:in `<main>'

```

**Comment by waferbaby** [comment]
Yep, can reproduce this locally - let me dig.

**Comment by wocsigint** [comment]
Yes thank you !

**Comment by waferbaby** [comment]
Okay! Try again?

**Comment by wocsigint** [comment]
`dimples build`
```
/home/will/about/lib/dimples/post.rb:15: warning: already initialized constant Dimples::Post::FILENAME_DATE
/usr/local/lib/ruby/gems/2.4.0/gems/dimples-2.7.1/lib/dimples/post.rb:15: warning: previous definition of FILENAME_DATE was here
/home/will/about/lib/dimples/version.rb:4: warning: already initialized constant Dimples::VERSION
/usr/local/lib/ruby/gems/2.4.0/gems/dimples-2.7.1/lib/dimples/version.rb:4: warning: previous definition of VERSION was here
Building site at /home/will/about/site...
Done! Site built in 0.0 seconds.
```
There is nothing in site/

**Comment by waferbaby** [comment]
Yeah, that will happen when you're in the codebase for dimples itself, but that's okay.

**Comment by wocsigint** [comment]
Ok thanks !

**Comment by waferbaby** [comment]
And `site` will be empty because there's none of the expected files to build a site from (I really need to make a `dimples init` or something :)

**Comment by wocsigint** [comment]
Ok, this is my first time with ruby. I used to use Pelican or ikiwiki for blogging. `dimples init` will be great. If there is no init script how can I set up a site as quickly as possible ?

**Comment by waferbaby** [comment]
The readme has an example folder structure - let me know if that makes sense!

**Comment by wocsigint** [comment]
Nice, thank you.

**Comment by waferbaby** [comment]
No worries! Reopen an issue if you get stuck!
